Fixes to enable soji to run on OS X
joecannatti/soji pull request #13
Opened 2016-10-19 17:26 UTC by iacobus42

I made a few changes to soji to enable it to run on OS X. They are 

- soji used the `--date` flag with `date`. This is a GNU extension to `date`. To enable it to work on OS X and other non-GNU *nix systems, the flags needed to be changed. `date --date` is easily replaced by `date -jf`. See the answer by Dirk Eddelbuettel and comments at http://stackoverflow.com/questions/1842634/parse-date-in-bash for more details

- OS X `date` requires the `-v` flag to add time to the present date

- `awk` in OS X would issue a warning when `-F ''` was used. To suppress this warning, I changed it to use `-FS=,`.

- OS X installs things in different locations. I changed the shebang at the start of `soji` and `soji.scm` to point to the guile at `/usr/local/bin` and not `/usr/bin`.(More on this later) OS X won't let you install to `/usr/bin` even with sudo unless you disable some OS protection features so it is often just easier to install to `/usr/local/bin` and deal with it.

- OS X won't let you install soji to `/usr/bin`. In the Makefile I changed the install location for soji to `/usr/local/bin/soji` from `/usr/bin/soji`

- When testing on OS X, cronjobs weren't properly running any code located in `/usr/local/bin` unless I provided the full path.

- `notify-send` doesn't work on OS X as far as I can tell. I used the terminal-notifier project by julienXX (https://github.com/julienXX/terminal-notifier) to provide for OS notifications based on the cron jobs in OS X

- I used the brightness project by nriley (https://github.com/nriley/brightness) to adjust the screen brightness using cron jobs. It only changes the brightness of the primary screen. On my MBP, only the laptop brightness changes. I have no idea how it works on a desktop. The external monitors do not change and as far as I can tell OS X has no provision for changing them.

I used the `uname` to determine if the system is on OS X or not and run the correct code accordingly (OS X if the `uname -a` contains `Darwin`). It only uses the OS X specific code when on OS X, otherwise it runs the original soji code. 

Since OS X and Ubuntu have different shebangs and paths required, I wrote a version of the files `soji`, `soji.scm` and `Makefile` with the appended OS (`for_linux` or `for_os_x`). I then wrote a very simple script to use `mv` the system specific files to the generic names (e.g., on OS X, `soji_for_os_x` becomes `soji`) and then run `make install`. A user should be able to install soji on either Ubuntu or OS X by just running `sudo sh install_soji`. 

I have tested the repo on Ubuntu and OS X El Capitan.

2016-10-19 18:49 UTC, joecannatti commented
Thanks for all this work @iacobus42 !

I will review this PR in detail this evening, but it all looks good with a quick glance.

2016-10-20 02:50 UTC, iacobus42 commented
I added testing with travis to cover OS X but the OS X jobs don't seem to be starting on Travis. The OS X testing environment seems very (very) slow to start. Build 114 passed both - Build 115 (currently running) is the same as Build 114 but with an updated `README.md` covering the OS X-specific dependences.

2016-10-20 16:33 UTC, joecannatti requested changes
Thanks so much! Just a couple of small comments, then I'll merge. I may take a pass at minimizing some of the difference between the OS X and Linux versions after the merge. But this is great.

2016-10-20 16:33 UTC, joecannatti commented on subcommands/status
> +#!/usr/bin/env bash
Can you take out these blank lines and extra shebang?

2016-10-20 16:33 UTC, joecannatti commented on subcommands/status
> +if [ "$os_x" != "" ]; then
Does this file need 
```
os_x=`uname -a | fgrep -i 'Darwin'` 
```
at the top, like the others?

2016-10-20 16:33 UTC, joecannatti commented on subcommands/bright
> +    DISPLAY=:0 xrandr --output $disp --display ":0" --brightness 1 || true
indent that line under the `for` please

2016-10-20 16:35 UTC, iacobus42 commented on subcommands/status
> +if [ "$os_x" != "" ]; then
Yes, I actually discovered that this morning. My ~/.config/soji/subcommands had an outdated build on my machine from when I was just focused on getting the OS/X issues worked out. That is corrected in the current build.

2016-10-20 16:36 UTC, iacobus42 commented on subcommands/status
> +#!/usr/bin/env bash
Removed.

2016-10-20 16:36 UTC, iacobus42 commented on subcommands/bright
> +    DISPLAY=:0 xrandr --output $disp --display ":0" --brightness 1 || true
Done.

2016-10-20 16:37 UTC, joecannatti commented
I've had trouble in the past with the OS X builds on Travis. I'm okay with merging it without that working and I can play around with it later.

2016-10-20 16:39 UTC, iacobus42 commented
I just pushed your requested edits. The OS X travis tests are passing but it takes about 15-20 minutes for the OS X jobs to even start.

Thanks!

2016-10-21 02:00 UTC, joecannatti approved these changes

2016-10-21 02:01 UTC, merged